name: Test
on: [push]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Install Rust cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: cargo
      - name: Install Scryer Prolog
        uses: logtalk-actions/setup-scryer-prolog@master
        with:
          scryer-prolog-version: 0.8.127
      - name: Install Logtalk
        uses: logtalk-actions/setup-logtalk@master
        with:
          logtalk-version: 3.50.0
      - name: Checkout
        uses: actions/checkout@v2
      - name: Execute tests
        run: logtalk_tester -p scryer